export enum CREATIVES {
  GET_REQUEST = "CREATIVES_GET_REQUEST",
  GET_SUCCESS = "CREATIVES_GET_SUCCESS",
  GET_FAILED = "CREATIVES_GET_FAILED",
  SET_REQUEST = "CREATIVES_SET_REQUEST",
  SET_ALL_CHECKBOXES = "SET_ALL_CHECKBOXES",
  SET_CHECKBOX_STATE = "SET_CHECKBOX_STATE",
  SET_CAMPAIGNS_SELECTED = "SET_CAMPAIGNS_SELECTED",
  SET_ALL_CAMPAIGNS_SELECTED = "SET_ALL_CAMPAIGNS_SELECTED",
  SET_DEFAULT_STATE = "SET_DEFAULT_STATE",
  CLEAN_STATE = "CLEAN_STATE",
}
