export enum PRODUCTS {
  GET_REQUEST = "PRODUCTS_GET_REQUEST",
  GET_SUCCESS = "PRODUCTS_GET_SUCCESS",
  GET_FAILED = "PRODUCTS_GET_FAILED",
  GET_CREATIVES_SUCCESS = "GET_CREATIVES_SUCCESS",
  GET_CAMPAIGNS_SUCCESS = "GET_CAMPAIGNS_SUCCESS",
  GET_LOGS_SUCCESS = "GET_LOGS_SUCCESS",
}
